trigger: none

parameters:

- name: resourceGroup
  displayName: Resource Group Name
  type: string
  default: rg-devops

- name: keyVaultName
  displayName: Key Vault Name
  type: string
  default: kv-devops-demo

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self


- task: AzureCLI@2
  displayName: 'Create KeyVault and Upload JSON File'

  inputs:

    azureSubscription: 'My Managed identity'

    scriptType: bash

    scriptLocation: inlineScript

    inlineScript: |

      RESOURCE_GROUP="${{ parameters.resourceGroup }}"

      LOCATION="northeurope"

      KEYVAULT_NAME="${{ parameters.keyVaultName }}"

      SECRET_NAME="dtaeunprodlappint01-i3910-sa-secret"

      JSON_FILE="$(Build.SourcesDirectory)/secret/my_secret.json"


      echo "Resource Group: $RESOURCE_GROUP"

      echo "KeyVault: $KEYVAULT_NAME"


      echo "Checking Key Vault..."


      if ! az keyvault show \
          --name "$KEYVAULT_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          > /dev/null 2>&1
      then

          echo "Creating Key Vault..."

          az keyvault create \
            --name "$KEYVAULT_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$LOCATION"

      else

          echo "Key Vault already exists"

      fi


      echo "Uploading JSON file as secret..."


      az keyvault secret set \
          --vault-name "$KEYVAULT_NAME" \
          --name "$SECRET_NAME" \
          --file "$JSON_FILE"


      echo "Secret upload completed."
